# Generated by Django 4.0.6 on 2022-09-01 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminusername', models.CharField(max_length=20)),
                ('adminpassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmusername', models.CharField(max_length=20)),
                ('mmpassword', models.CharField(max_length=20)),
                ('mmrole', models.CharField(default='', max_length=20)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userusername', models.CharField(default='', max_length=20)),
                ('userpassword', models.CharField(default='', max_length=20)),
                ('userserverdetails', models.CharField(max_length=100)),
                ('usersenddate', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('userlicenseno', models.CharField(max_length=25)),
                ('userfile', models.FileField(upload_to='')),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llapp.master')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llapp.master'),
        ),
    ]
